function [fitresult, gof] = createFit(D, FS)
%CREATEFIT(D,FS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : D
%      Y Output: FS
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Feb-2019 01:05:47


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( D, FS );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'FS vs. D', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel D
ylabel FS
grid on


